name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework 4.8
      uses: microsoft/setup-msbuild@v1

    - name: Install Windows SDK with Signing Tools
      uses: ChristopheLav/windows-sdk-install@v1
      with:
        version-sdk: '22621'  # Specify the desired SDK version
        features: 'OptionId.SigningTools'  # Install the Signing Tools feature

        
    - name: Debug: List Windows SDK directories
      run: dir "C:\Program Files (x86)\Windows Kits\10\bin" /s

  
    - name: Add signtool to PATH
      run: |
        $env:Path += ';C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64'
      shell: powershell

    - name: Restore dependencies
      run: nuget restore

    - name: Build the project
      run: msbuild /p:Configuration=Release
