name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Windows SDK
      run: choco install windows-sdk-10-version-1903-all --ignore-checksums

    - name: Add signtool to PATH
      run: |
        $env:Path += ";C:\Program Files (x86)\Windows Kits\10\bin\x86"
        $env:Path += ";C:\Program Files (x86)\Windows Kits\10\bin\x64"
        Write-Output "Updated PATH: $env:Path"

    - name: Setup .NET Framework 4.8
      uses: microsoft/setup-msbuild@v1

    - name: Restore dependencies
      run: nuget restore

    - name: Build the project
      run: msbuild /p:Configuration=Release
