name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework 4.8
      uses: microsoft/setup-msbuild@v1

      
    - name: Install Windows SDK
      run: choco install windows-sdk-10.0 -y

    - name: Confirm signtool availability
      run: dir "C:\Program Files (x86)\Windows Kits\10\bin" /s | find "signtool.exe"
    - name: Find and Add signtool to PATH
      run: |
        $signtoolPath = Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits\10\bin" -Filter "signtool.exe" -Recurse | Select-Object -ExpandProperty DirectoryName
        if ($signtoolPath) {
          $env:Path += ";$signtoolPath"
          Write-Host "Added signtool.exe to PATH: $signtoolPath"
        } else {
          Write-Error "signtool.exe not found in Windows Kits directory."
        }
      shell: powershell



    - name: Restore dependencies
      run: nuget restore

    - name: Build the project
      run: msbuild /p:Configuration=Release
